package javaee.web.hr.entity;



import javaee.web.hr.entity.Employee;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="DEPARTMENT"
    ,schema="HR"
)
public class Department  implements java.io.Serializable {


     private short departmentId;
     private Employee employee;
     private String departmentName;
     private Set employees = new HashSet(0);

    public Department() {
    }

	
    public Department(short departmentId, String departmentName) {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
    }
    public Department(short departmentId, Employee employee, String departmentName, Set employees) {
       this.departmentId = departmentId;
       this.employee = employee;
       this.departmentName = departmentName;
       this.employees = employees;
    }
   
     @Id 

    
    @Column(name="DEPARTMENT_ID", unique=true, nullable=false, precision=4, scale=0)
    public short getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(short departmentId) {
        this.departmentId = departmentId;
    }

    
  

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MANAGER_ID")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="DEPARTMENT_NAME", nullable=false, length=30)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


